services:
  # PostgreSQL database service for production.  Container names are
  # deliberately omitted so that Docker Compose will automatically
  # prefix service names with the project name.  Exposing the port
  # allows connections from the host for debugging and backups.
  postgres:
    ports:
      - "10010:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # FastAPI application service.  It relies on the Dockerfile in this
  # repository and will be built via the CI/CD pipeline.  The port
  # mapping exposes the service on 8082 by default.
  fastapi:
    ports:
      - "10012:8000"

  # Redis cache service.  The port mapping can be adjusted if needed.
  redis:
    ports:
      - "10014:6379"

volumes:
  # Named volume for PostgreSQL data.  Docker Compose will prefix
  # this volume with the project name when creating it (for example,
  # ``myproject_postgres-data``) to avoid collisions between
  # different environments.
  postgres-data:
