services:
  postgres:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - my_network
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: >
      gunicorn main:app
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:8000
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:latest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
