services:
  postgres:
    container_name: survive_postgres
    ports:
      - "3333:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  fastapi:
    container_name: survive_fastapi
    ports:
      - "8082:8000"

  redis:
    container_name: survive_redis
    ports:
      - "6380:6379"

volumes:
  postgres-data:
