services:
  postgres:
    container_name: survive_dev_postgres
    env_file: .env.test
    ports:
      - "3334:5432"
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data

  fastapi:
    container_name: survive_dev_fastapi
    env_file: .env.test
    ports:
      - "8083:8000"

  redis:
    container_name: survive_dev_redis
    ports:
      - "6381:6379"

volumes:
  postgres-data-dev:
